from pathlib import Path

ROOT = Path(__file__).parents[1]
RESOURCES = ROOT / "resources"
TEMPLATES = RESOURCES / "templates"
EXAMPLES = ROOT / "examples"

STATE_GAIN = "STATE_GAIN"
STATE_TILT = "STATE_TILT"
STATE_INPUT_POWER = "STATE_INPUT_POWER"
STATE_OUTPUT_POWER = "STATE_OUTPUT_POWER"
STATE_SERVICE = "STATE_SERVICE"

CONFIG_GAIN = "CONFIG_GAIN"
CONFIG_TILT = "CONFIG_TILT"
CONFIG_OUTPUT_ENABLED = "CONFIG_OUTPUT_ENABLED"
CONFIG_RANGE = "CONFIG_RANGE"
CONFIG_MODE = "CONFIG_MODE"
CONFIG_POWER = "CONFIG_POWER"



